.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "RustOwl Language Server" 1  "RustOwl Language Server 0.2.3" 
.SH NAME
RustOwl Language Server
.SH SYNOPSIS
\fBrustowl\fR [\fB\-\-stdio\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-stdio\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
RustOwl Language Server\-check(1)
.TP
RustOwl Language Server\-clean(1)
.TP
RustOwl Language Server\-toolchain(1)
.TP
RustOwl Language Server\-completions(1)
Generate shell completions
.TP
RustOwl Language Server\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.2.3
.SH AUTHORS
cordx56 <cordx56@cordx.cx>
