name: Generate Changelog

on:
  workflow_dispatch:

jobs:
  changelogen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          docker pull quay.io/git-chglog/git-chglog:latest
          docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog --tag-filter-pattern '^v\d+\.\d+\.\d+$' -o CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            CHANGELOG.md
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          base: main
          branch: create-pull-request/autogenerate-changelog
          commit-message: "chore: update changelog"
          title: "Update Changelog"
